### Урок 3. TensorFlow#

### -- Автор: Шенк Евгений Станиславович

### Задание 1.
<ol>
Попробуйте улучшить работу нейронной сети(разобранную на уроке) обучавшейся на датасет Fashion-MNIST. 
Опишите в комментарии к уроку - какого результата вы добились от нейросети? Что помогло вам улучшить ее точность?
</ol>

Как и в случае с Keras изменение основных параметров дало улучшение метрики accuracy, увеличили количество эпох, нейронов на внутреннем слое, изменили оптимизатор:  
было: epoch=3; 'relu' -> loss: loss: 0.6322 - accuracy: 0.7611  
стало: epoch=10; dence 512; 'relu'; 'Adamax' -> loss: 0.4946 - accuracy: 0.8641  

### Задание 3.
<ol>
Попробуйте обучить нейронную сеть на TensorFlow 2 на датасете imdb_reviews. Опишите в комментарии к уроку - какой результата вы добились от нейросети? Что помогло вам улучшить ее точность?
</ol>

В данном случае за основу была взята сеть из документации: https://www.tensorflow.org/tutorials/keras/text_classification_with_hub  

В отличие от презыдущего задания во входном слое здесь будет использоваться предварительно обученная модель встраивания текста из "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1" для преобразования предложений в векторы. Остальная часть сети выглядит примерно так же как и в задании 1.  

Результат по умолчанию: loss: 0.324; accuracy: 0.858  

Изменение параметров модели: Эпохи, батчи, оптимизатор, количество нейронов на внутреннем слое и т.д. улучшений не давали или ухудшали модель (Пораметры модели из документации подобраны оптимально). Изменение модели в первом слое на другую "https://tfhub.dev/google/tf2-preview/nnlm-en-dim128/1" (model with ~1M vocabulary size and 128 dimensions) так же не улучшило качество, зато увеличило время обработки модели в 30-40 раз, результат: loss: 0.524; accuracy: 0.850.  

### Далее идет код к заданиям:

### Задание 1.

<ol>
    <li>Попробуйте улучшить работу нейронной сети(разобранную на уроке) обучавшейся на датасет Fashion-MNIST. 
       Опишите в комментарии к уроку - какого результата вы добились от нейросети? Что помогло вам улучшить ее точность?</li>
</ol>

In [17]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
import tensorflow_hub as hub
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt

In [2]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [3]:
np.random.seed(2177)
tf.random.set_seed(2177)

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(512, activation='relu'), # 128
    keras.layers.Dense(10)
])

In [4]:
model.compile(optimizer='Adamax',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [5]:
model.fit(train_images, train_labels, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 3s 2ms/step - loss: 8.1237 - accuracy: 0.7761
Epoch 2/10
1875/1875 [==============================] - 3s 2ms/step - loss: 1.3287 - accuracy: 0.8029
Epoch 3/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.5141 - accuracy: 0.8368
Epoch 4/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4136 - accuracy: 0.8582
Epoch 5/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3693 - accuracy: 0.8705
Epoch 6/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3374 - accuracy: 0.8793
Epoch 7/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3206 - accuracy: 0.8838
Epoch 8/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3079 - accuracy: 0.8883
Epoch 9/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2950 - accuracy: 0.8929
Epoch 10/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.283

In [6]:
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print('\nTest accuracy:', test_acc)

313/313 - 0s - loss: 0.4946 - accuracy: 0.8641

Test accuracy: 0.8640999794006348


In [7]:
# epoch=3; 'relu' -> loss: loss: 0.6322 - accuracy: 0.7611

# epoch=3; dence 512; 'relu' -> loss: 0.5741 - accuracy: 0.8174
# epoch=3; dence 128 x2; 'relu' -> loss: 0.5869 - accuracy: 0.8113

# epoch=5; 'relu' -> loss: 0.6374 - accuracy: 0.7840

# epoch=10; 'relu' -> loss: 0.5039 - accuracy: 0.8294
# epoch=10; dence 128 x2; 'relu' -> loss: 0.4477 - accuracy: 0.8427
# epoch=10; dence 1024 x2; 'relu' -> loss: 0.4290 - accuracy: 0.8445

# epoch=5; 'elu' -> loss: 0.6522 - accuracy: 0.7762

In [8]:
# epoch=10; dence 512; 'relu'; 'Adamax' -> loss: 0.4946 - accuracy: 0.8641

### Задание 3.

Попробуйте обучить нейронную сеть на TensorFlow 2 на датасете imdb_reviews. Опишите в комментарии к уроку - какой результата вы добились от нейросети? Что помогло вам улучшить ее точность?

In [9]:
# https://www.tensorflow.org/tutorials/keras/text_classification_with_hub

In [10]:
import tensorflow_datasets as tfds
import dataget

In [100]:
train_data, test_data = tfds.load(
    name="imdb_reviews", 
    split=('train[:60%]', 'test'),
    as_supervised=True)

In [101]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(3)))
train_examples_batch

<tf.Tensor: shape=(3,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell a

In [102]:
train_labels_batch

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 0, 0], dtype=int64)>

In [103]:
# embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
embedding = "https://tfhub.dev/google/tf2-preview/nnlm-en-dim128/1"
hub_layer = hub.KerasLayer(embedding, input_shape=[], 
                           dtype=tf.string, trainable=True)
hub_layer(train_examples_batch[:3])

<tf.Tensor: shape=(3, 128), dtype=float32, numpy=
array([[ 9.01966274e-01, -4.83913347e-03,  1.17907055e-01,
         3.81319046e-01,  6.57222793e-02, -3.01581532e-01,
         8.90584365e-02, -2.69034863e-01, -8.51345584e-02,
         1.08877886e-02, -6.66372627e-02, -3.73063087e-01,
        -2.76447266e-01, -1.87254980e-01,  5.67507632e-02,
         9.09779966e-02, -6.24961555e-02, -3.28687276e-03,
        -3.08512092e-01,  3.78482223e-01,  7.62880966e-02,
         1.43733576e-01, -1.12897493e-01,  9.59761534e-03,
        -2.38938913e-01,  2.93743908e-02,  7.28663057e-02,
        -2.48727947e-02, -8.16893280e-02,  6.68320432e-02,
        -5.62225394e-02,  2.47078985e-01,  1.17681175e-01,
         3.17581035e-02,  2.65932620e-01, -1.37706831e-01,
        -1.50708258e-01, -1.63614675e-01, -1.51269153e-01,
         2.34616160e-01, -9.12236273e-02, -4.22684886e-02,
        -1.01224177e-01, -2.12229744e-01,  6.74503446e-02,
         1.85163647e-01,  3.62982228e-02, -3.50210071e-01,
      

In [104]:
np.random.seed(2177)
tf.random.set_seed(2177)

model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1))

model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer_6 (KerasLayer)   (None, 128)               124642688 
_________________________________________________________________
dense_23 (Dense)             (None, 16)                2064      
_________________________________________________________________
dense_24 (Dense)             (None, 1)                 17        
Total params: 124,644,769
Trainable params: 124,644,769
Non-trainable params: 0
_________________________________________________________________


In [105]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [106]:
history = model.fit(train_data.shuffle(10000).batch(512),
                    epochs=20,
                    validation_data=train_data.batch(512),
                    verbose=1)

Epoch 1/20
30/30 [==============================] - 45s 2s/step - loss: 0.6219 - accuracy: 0.5633 - val_loss: 0.5041 - val_accuracy: 0.7225
Epoch 2/20
30/30 [==============================] - 44s 1s/step - loss: 0.4193 - accuracy: 0.8057 - val_loss: 0.3097 - val_accuracy: 0.8721
Epoch 3/20
30/30 [==============================] - 43s 1s/step - loss: 0.2631 - accuracy: 0.8979 - val_loss: 0.1931 - val_accuracy: 0.9403
Epoch 4/20
30/30 [==============================] - 43s 1s/step - loss: 0.1705 - accuracy: 0.9433 - val_loss: 0.1238 - val_accuracy: 0.9634
Epoch 5/20
30/30 [==============================] - 43s 1s/step - loss: 0.1113 - accuracy: 0.9699 - val_loss: 0.0788 - val_accuracy: 0.9811
Epoch 6/20
30/30 [==============================] - 43s 1s/step - loss: 0.0708 - accuracy: 0.9844 - val_loss: 0.0494 - val_accuracy: 0.9924
Epoch 7/20
30/30 [==============================] - 43s 1s/step - loss: 0.0451 - accuracy: 0.9932 - val_loss: 0.0320 - val_accuracy: 0.9974
Epoch 8/20
30/30 [==

In [107]:
results = model.evaluate(test_data.batch(512), verbose=2)

for name, value in zip(model.metrics_names, results):
    print("%s: %.3f" % (name, value))

49/49 - 12s - loss: 0.5242 - accuracy: 0.8499
loss: 0.524
accuracy: 0.850
